git-publish
If GIT_EDITOR is "emacs -nw" (containing a whitespace),
subcommand.call() will fail.
Split the variable with whitespace.
Reported by: David Gibson <dgibson@redhat.com>
=> Fix $GIT_EDITOR invocation if it has whitespace

README.rst, git-publish
Hi Stefan:
The first patch changes CC options to cascade between profile, history, and CLI.
Patch 2 adds a flag to delete Saved CCs.
Patch 3 adds a flag to overwrite Saved and Profile CCs with CLI CCs.
This is to allow profiles with built-in CC options to cascade with Command Line options. For example: a qemu-block profile might specify:
[gitpublishprofile "block"]
to = qemu-block@nongnu.org
cc = qemu-devel@nongnu.org
but we'd still like to be able to specify additional CC options on the command-line, so allowing them to cascade is useful.
Take what seems useful, NACK what doesn't. :octocat:
=> Cascading CC options

git-publish
Git branches created with "git checkout -b $BRANCH" command has a
default "." remote in .git/config. When sending pull requests in such a
branch, the per profile remote setting is masked.
Such a remote is obviously meaningless for pull requests, so simply
ignore it and fall through to the profile var if any.
=> Ignore the default "." remote

git-publish
This is a parameter known by git-format-patch command. Since we still
don't have a per-repository way to store subject prefix for series,
it'll be good to have it.
Another natural benefit for this: git-publish naturally becomes
compatible with git-format-patch. For example, if people just switched
to use git-publish from originall git-format-patch, they would not need
to bother specify subject prefix again.
Here "format.subjectprefix" is having the lowest priority to make sure
old git-publish users (with profiles) are not affected.
Signed-off-by: Peter Xu <peterx@redhat.com>
=> Support "format.subjectprefix" in git-format-patch

git-publish
The --setup operation does not operate on a git repo and should work
even when the current working directory is outside a git repo.  The
profile code was querying the git repo before the --setup code.  This
caused a backtrace.
Fixes #20
Signed-off-by: Stefan Hajnoczi <stefanha@gmail.com>
=> Make --setup work outside a git repo again

git-publish
According to man git-config(1), this is the preference order to follow
for the remote to push to.
=> pull-request: use pushDefault/pushRemote preferably

git-publish
Do not ignore error code command exit if the command is crucial to
some operation. Print stderr in this case.
=> Fail on some git command errors

README.rst, git-publish
This is to use --notes of git format-patch. It includes git-notes(1)
into the patch description, after the three-dash line ---.
Signed-off-by: Anthony PERARD <anthony.perard@citrix.com>
=> Add --notes options

git-publish
The cc we've got so far is a list of unicode strings, but here the
output is raw string (byte array). The following union operation
shouldn't mix these two types. Explicitly decode it like in
popen_lines().
Reported-by: Peter Xu <peterx@redhat.com>
=> Fix encoding of cc_cmd

git-publish
With Python 2, file.write implicitly tries to encode the joined list as
'ascii' which will not work if there are non-ascii being written.
Be explicit with the encoding to fix that.
=> Fix edit_email_list

git-publish
In rare cases we need to select which patches to send instead of all.
One example is the revised pull requests in QEMU which may omit the
unchanged patches.
=> add "s" menu command

git-publish
when running "git publish" outside of a repository this makes the
difference between
```
...
File "/usr/bin/git-publish", line 130, in git_get_toplevel_dir
GIT_TOPLEVEL = _git('rev-parse', '--show-toplevel')[0]
IndexError: list index out of range
```
and
```
...
File "git-publish/git-publish", line 130, in git_get_toplevel_dir
GIT_TOPLEVEL = _git_check('rev-parse', '--show-toplevel')[0]
File "git-publish/git-publish", line 63, in _git_check
raise GitError('\n'.join(stderr))
__main__.GitError: fatal: Not a git repository (or any parent up to mount point /foo/bar)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```
Signed-off-by: Fabian Grünbichler <f.gruenbichler@proxmox.com>
=> check for errors when getting toplevel dir

debian/control
debhelper 11 is already in stretch-backports, but backports packages are always ordered between stable and stable+1 versions via the ~bpo9 suffix.
adding the ~ allows backported debhelper 11 packages to fulfill the versioned dependency, allowing for no-change backports.
Signed-off-by: Fabian Grünbichler <f.gruenbichler@proxmox.com>
=> debian: use backports-compatible debhelper version

git-publish, git-publish.pod
to support work flows where pushing an unsigned tag to an internal
git repository for review is acceptable.
Signed-off-by: Fabian Grünbichler <f.gruenbichler@proxmox.com>
=> make pull request signing configurable

git-publish
This helps running git-publish from a subdir (such as a build directory)
=> cccmd: run in the toplevel dir

git-publish, git-publish.pod
We can provide "TO" in three places:
- using "--to" parameter
- using "--profile" or "-p" and setup "TO" in the profiles
- using saved "TO" list in git config
For "CC" list we merge them.  For "TO" list we didn't.  Let's do the
same for "TO" list so that we always merge the "TO"s in all configs.
Signed-off-by: Peter Xu <peterx@redhat.com>
=> Merge "TO" list for various configurations

git-publish, git-publish.pod
blurb-template is particular useful when email messages needs to
follow a pre-defined pattern.
Using it makes the default message "*** BLURB HERE ***" to be
changed to something that can be pre-defined in .gitpublish
=> Adding blurb-template option to git-publish

git-publish, git-publish.pod
We may want to allow passing arbitrary arguments to format-patch, to
avoid proxying all of them. Eventually, it would be nice to have them
saved in a profile too.
(the one I am insterested in are those from
https://github.com/tianocore/tianocore.github.io/wiki/Laszlo's-unkempt-git-guide-for-edk2-contributors-and-maintainers)
=> RFC: Allow to pass arbitrary arguments to format-patch

README.md
Users may be unaware that it's safe to simply copy or symlink `git-publish` to some directory on `$PATH`. Add explicit manual install instructions to `README.md`. Addresses issue #50.
=> Explicit manual install instructions

debian/control, git-publish, git-publish.pod
hi Stefan,
Here 2 patches:
- fix a warning for Debian
- support for multiple GPG keys, via the '--keyid' parameter
Thanks,
Phil.
=> Support for multiple GPG keys + Debian Piuparts

git-publish
Forcing 'utf-8' is quick and simple, but it's usually a good idea to respect a user locale, unless one is tightly controlling the encoding of written/read files, and the output produced by commands.
This is based on a "recipe" that has worked well on "avocado-land".
---
Changes from v1 (#54):
* Removed commit "Use builtin open()", as it regresses Python 2 support
=> Favor user (system) preferred encoding (and other trivial changes) [v2]

git-publish
Commit 395e55bec standardized the handling of data comming from the
execution of commands and when writing to files.  But, there are other
sources of data, such as from command line options, that when not
given a proper encoding, are treated as bytes.
On Python 2, there's implicit conversion when mixing unicode and bytes
(and strings are bytes on Python 2).  When that happens, the content
of the bytes part will be decode using an 'ascii' codec.  A reproducer
is as simple as:
>>> '\xc3\xa3' + u''
To avoid this implicit conversion, we need to manually standardize
the data into unicode.
Given that this is also intended to work on Python 3, a little type
check is necessary, given that something represented with quotes and
double-quotes in Python 3, is already an "unicode string" and thus, …
=> Further standardize bytes/text handling

git-publish, git-publish.pod
Add the git-format-patch --no-binary parameter that does not output contents of
changes in binary files.
=> Add support for the git-format-patch --no-binary parameter

git-publish
Instead of reporting an error when running git-publish on master branch *and*
not specifying any options, fail whenever the topic branch is a base
branch (i.e. when not using any topic branch).
Fixes #59
Signed-off-by: Martin Kletzander <nert.pinx@gmail.com>
=> Print error when publishing a base branch

git-publish
First time trying to use git-publish. The local .gitpublish config has 'base' set to a branch that I only exists on the remote and I haven't checked out locally. `git-publish` silently exits without giving me any hint.
`git format-patch` errors in this case trying to access a non-existent branch. First patch prints the GitError message in this case. Second patch amends the GitError message to contain the command string too.
=> Print error message and command string when git format-patch failed

git-publish
If '--no-binary' parameter is not specified, the options.binary
is None and the 'not binary' condition checked in the
git_format_patch() is True, so the '--no-binary' is always passed
to the git-format-patch.
This patch fix this issue, setting the default value
of '--no-binary' parameter to True.
Fixes: dad5ddcea3b661 ("Add --no-binary parameter")
Signed-off-by: Stefano Garzarella <sgarzare@redhat.com>
=> Fix the '--no-binary' behavior, adding default value

git-publish
The code that splits the message when a line starts with
`commit ` breaks when the actual tag message contains a line
starting with `commit `.  Using `git tag -l --format=%(message)`
will avoid that problem.
As `git tag -l` won't error out if the tag doesn't exist, now we
can just use `_git()` instead of ignoring stderr.
=> Use "git tag -l" to get tag message contents

git-publish
Python 2 EOL is in less than 3 months, and by using Python 3 by
default we will be able to catch python3-specific bugs before
it's too late.  Change the interpreter line to use python3.
I'm not removing the `__future__` imports because I don't know
yet if we want to drop Python 2 support immediately, or wait
until January.
Fixes #38.
=> Use python3 by default to run git-publish

git-publish
At commit cd2b4f588428 ("Use "git tag -l" to get tag message
contents"), I accidentally broke the handling of empty tag
messages in `git_tag_get_message()`.  The function was now
returning `['']` when a tag existed with an empty message, instead
of returning an empty list.
This broke the cover letter check at main(), making git-publish
always include a cover letter even if `--no-cover-letter` was
used.
Fix this by removing the last line at `git_tag_get_message()`.
=> Fix handling of empty tag messages

git-publish
Currently, git-publish fails when given the --add-header argument.
Usage: git-publish [options] -- [common format-patch options]
git-publish: error: no such option: --add-header
This change makes --add-header an official parameter.
It will be passed to format-patch, allowing the user to use
customized headers when using git-publish.
=> Add support for --add-header argument

git-publish
This patch fixes an issue when header.decode_header() is called in
Python 3 because in some cases it could return (str, NoneType) and
str doesn't provide the decode() attribute in Python 3, causing the
following exception:
Traceback (most recent call last):
File "/home/stefano/repos/git-publish/git-publish", line 867, in <module>
sys.exit(main())
File "/home/stefano/repos/git-publish/git-publish", line 828, in main
selected_patches = inspect_menu(tmpdir, to, cc, patches, suppress_cc,
File "/home/stefano/repos/git-publish/git-publish", line 460, in inspect_menu
print(parse_header(m['subject']))
File "/home/stefano/repos/git-publish/git-publish", line 428, in parse_header
r += h.decode(c)
AttributeError: 'str' object has no attribute 'decode'
Signed-off-by: Stefano Garzarella …
=> Fix parse_header() for Python 3

git-publish
This patch appends useful comments information in the cover letter,
shown in the editor. Information includes version number, branches,
to list, cc list, in-reply-to address, shortlog and the overall
diffstat.
This feature is enabled by default and can be disabled with the new
'--no-cover-info' parameter.
Suggested-by: David Gibson <david@gibson.dropbear.id.au>
Signed-off-by: Stefano Garzarella <sgarzare@redhat.com>
=> Show patch series status comment into cover letter

testing/0000-gitconfig-home, testing/run_tests.sh
If the system git user name and email are not set, the create_git_repo() fails with this error:
```
> ./testing/run_tests.sh
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: unable to auto-detect email address
````
This PR set a fake git user name and email in the fake home directory to solve this issue and add a little change to testing/0000-gitconfig-home to work with this change.
=> testing: set fake user name and email in .gitconfig

git-publish
Use the utility function which does the right thing to retrieve the
.git directory.
=> Fix --edit in worktree

git-publish
Hello Stefan,
The first patch is a fix when signing pullrequests with multiple keys,
the second a follow-up cleanup (call git-tag with long options),
I find the third patch convenient (use date in tag name),
finally the last patch improves usability when servers enforce limits on series.
Regards,
Phil.
=> Fix --keyid option, ignore relogin-delay

git-publish
Fix #85 by always specifying `--batch-size=0` when using `--relogin-delay=0`.
=> Use --batch-size when using --relogin-delay

git-publish
This will fix the issue of --in-reply-to when there're more than one patch to
be sent.  Before this patch, --in-reply-to will only work correctly for the 1st
patch of the patchset, but not all of them.  The problem is the command line:
git-send-email PATCH1 PATCH2 PATCH3 ...
Will always let PATCH2/PATCH3/... to reply to PATCH 1 even if --in-reply-to is
specified.  In other words, "--in-reply-to" for git-send-email only applied
correctly on PATCH1, but not on all the patches.
Assuming we've sent the cover letter and 2 patches already, but we still want
to continue send the patches 3-5.  Before this patch, the final patchset will
look like (after both old/new patchsets):
old cover letter
old patch 1
old patch 2
new patch 3
new patch 4
new patch 5
After this patch, it should become:
old …
=> Fix --in-reply-to with more than one patches

git-publish
git-send-email seems to be not happy with a cover letter already
encoded. In fact, git-format-patch generates it without encoding.
This problem occurs especially if 'sendemail.transferEncoding' is
not set to auto.
To avoid issues, instead of using the 'email' module, which encodes the
final result, we simply replace the text in the cover letter file
generated by git-format-patch.
Fixes: #88
Signed-off-by: Stefano Garzarella <sgarzare@redhat.com>
=> Avoid to encode the cover letter

.github/workflows/ci.yml, git-publish, testing/0005-subject-line-wrap, testing/0006-no-ascii-chars, testing/0007-subject-empty, testing/fake_git
Handling the cover letter as `mbox` has carried several issues (#88 #95 #96).
It seems that `git-send-email` doesn't expect an `mbox`, so let's handle the cover letter like a normal text, taking care of long 'Subject' line.
I also added a new test case for no-ascii characters (#96)
=> Do not handle the cover letter as mbox 

git-publish
"git format-patch --cover-letter" populates the body with the branch
description instead of the placeholder text by default. This prevents
"git publish" to replace it with the actual body that is kept in the
<branch>-staging tag.
Just tell "git format-patch" to only populate with the placeholder text.
Fixes #105 
Signed-off-by: Greg Kurz <groug@kaod.org>
=> Don't pick up the branch description in the cover letter

git-publish
The NamedTemporaryFile can not be opened by other editor. so we use
tempfile.mkstemp(text=True) instead.
[c] Edit Cc list in editor (save after edit)
[t] Edit To list in editor (save after edit)
[e] Edit patches in editor
[s] Select patches to send (default: all)
[p] Print final email headers (dry run)
[a] Send all
[q] Cancel (quit)
s
Traceback (most recent call last):
File "git-publish.py", line 905, in <module>
sys.exit(main())
File "git-publish.py", line 862, in main
selected_patches = inspect_menu(tmpdir, to, cc, patches, suppress_cc,
File "git-publish.py", line 514, in inspect_menu
listfile.write("\n".join(patches).encode(ENCODING))
TypeError: sequence item 0: expected str instance, bytes found
The notepad.exe complains
The other program are using this file, the process can not …
=> Fixes git-publish on Windows.

git-publish, git-publish.pod
If git-send-email fails after sending only some (say N) of the patches, invoking git-publish to send the rest currently involves:
- Manually choosing [s] and removing the first N lines;
- Manually adding In-Reply-To: and References: headers to every remaining patch pointing at the already-sent cover letter (assuming we want every email to be a reply to the first).
Add a couple options to streamline this process, so that if git-send-email fails after sending 3 out of 5 emails, we can simply do:
```console
$ git publish --skip=3 --no-thread --in-reply-to=20220513155418.2486450-1-afaria@redhat.com
```
=> Simplify recovery after git-send-email fails halfway through the patches

git-publish
- Fix usage of `open()` and `os.fdopen()` to ensure that files are closed properly.
- Use `open()` instead of `io.open()` (python 2 leftover)
- Idiomatic use of try-finally to cleanup temporary file
- Remove unneeded `__future__` imports (python 2 leftover)
- Remove unused import
=> General cleanups

git-publish
When the base branch does not exist, git-publish produces a pretty cryptic error:
ERROR: git format-patch --subject-prefix PATCH --output-directory /tmp/tmps35kpt7n --no-cover-letter master.. fatal: ambiguous argument 'master..': unknown revision or path not in the working tree. Use '--' to separate paths from revisions, like this: 'git <command> [<revision>...] -- [<file>...]'
Improve the situation a bit with an early check, and some hint.
=> Check the base branch

git-publish, git-publish.pod
Implement a way to forward args down to the git-send-email call. In this way you can access all git-send-emails features.
In my case I wanted to the cc-cmd to set cc per patch email instead for all of them. And though I can do what I want after applying this patch, it opens the door for using all kinds of features from git-send-email.
The only downside I see is that there might be clashes with git-publish specific options. If this is a concern, I can try to mitigate specific clashes.
comments are appreciated
=> Add arg that forwards args to git-send-email command
